import { Inter } from "next/font/google";
import "../../app/globals.css";
import Sidemenu from '../../components/Sidemenu';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ediprint",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidemenu/>
        {children}
      </body>
    </html>
  );
}
